bot:
  name: onlineuzbeknewbot
  token: 6723296213:AAGQ32RDVUc0Hee7F2szCK3VsBtvdyhQZYA
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:16825/railway
    username: postgres
    password: GdB2dD4-a*EBF36aBAc*ceeBbBB6CDEF
    name: Online-shop-bot
  sql:
    init:
      mode: always
upload:
  folder: C:\files\onlayn-shop-bot/upload/





#bot:
#  name: onlineuzbeknewbot
#  token: 6723296213:AAGQ32RDVUc0Hee7F2szCK3VsBtvdyhQZYA
#spring:
#  main:
#    allow-circular-references: true
#  datasource:
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
#    username: ${PROD_USERNAME}
#    password: ${PROD_PASSWORD}
#    name: spring-blog
#  sql:
#    init:
#      mode: always
#upload:
#  folder: C:\files\onlayn-shop-bot/upload/