server:
  port: 8081
bot:
  name: murket_uz_orgbot
  token: 6578822586:AAFXtVI8cTkfPaRBlhxXGZMiOniH4X-WyII
spring:
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://dpg-cl972tn6e7vc73aemj8g-a.oregon-postgres.render.com:5432/mydb_teuw
    username: postgresql
    password: Enh4j0OgB2zqfI3GF65hzXi0kxUWfzWH
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
upload:
  folder: C:\files\onlayn-shop-bot/upload/